### ISSUE TITLE
Error whmcs 8.1.3 php7.2

### ISSUE THREAD

**Issue by aroundfigures** [markustenghamn/WHMCS-Affiliates-Anywhere#3]
```
ArgumentCountError: Too few arguments to function select_query(), 2 passed in /www/Production/Alojamento/minehost/www.minehost.pt/public_html/manager/modules/addons/anveto_affiliate_anywhere_plus/anveto_affiliate_anywhere_plus.php on line 571 and at least 3 expected in /www/Production/Alojamento/minehost/www.minehost.pt/public_html/manager/includes/dbfunctions.php:0
Stack trace:
#0 /www/Production/Alojamento/minehost/www.minehost.pt/public_html/manager/modules/addons/anveto_affiliate_anywhere_plus/anveto_affiliate_anywhere_plus.php(571): select_query('mod_anveto_affi...', 'id,domainname')
#1 /www/Production/Alojamento/minehost/www.minehost.pt/public_html/manager/admin/addonmodules.php(0): anveto_affiliate_anywhere_plus_output(Array)
#2 {main}
```

**Comment by uberswe** [comment]
Hey @aroundfigures and thank you for opening a PR. This addon was last updated about 5 years ago and both WHMCS and PHP has had a few updates since then which has caused compatibility issues with this plugin. I no longer have access to WHMCS so I have no way of maintaining or testing this plugin.

I will mark this PR as help-wanted in the hopes that someone might find a fix and open a PR to this repository.
